BGAWebApp/Models/Game.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BGAWebApp.Models
{
    public class Game
    {
        public int Id { get; set; }
        public string? Title { get; set; }

        [Column(TypeName = "decimal(18, 2)")]
        public decimal Rating { get; set; }
        public string? RecommendCount { get; set; }

        public string? BestCount { get; set; }

        public string? SupportCount { get; set; }

        public string? Link { get; set; }
    }
}

BGAWebApp/Controllers/GamesController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BGAWebApp.Data;
using BGAWebApp.Models;

namespace BGAWebApp.Controllers
{
    public class GamesController : Controller
    {

        private readonly BGAWebAppContext _context;

        public GamesController(BGAWebAppContext context)
        {
            _context = context;
        }

        // GET: Games
        public async Task<IActionResult> Index(string numPlayers, string numQuality)
        {
            var games = from m in _context.Game
                         select m;

            ViewBag.numPlayers = numPlayers;

            if (!String.IsNullOrEmpty(numPlayers))
            {
                if (numQuality == "support")
                {
                    games = games.Where(s => s.SupportCount!.Contains(numPlayers) || s.RecommendCount!.Contains(numPlayers) || s.BestCount!.Contains(numPlayers)).OrderByDescending(game => game.Rating);
/*                    ViewBag.SupportGames = games.Where(s => s.SupportCount!.Contains(numPlayers));
                    ViewBag.RecommendGames = games.Where(s => s.RecommendCount!.Contains(numPlayers));
                    ViewBag.BestGames = games.Where(s => s.BestCount!.Contains(numPlayers));*/
                }
                else if (numQuality == "recommend")
                {
                    games = games.Where(s => s.RecommendCount!.Contains(numPlayers) || s.BestCount!.Contains(numPlayers)).OrderByDescending(game => game.Rating);
/*                    ViewBag.RecommendGames = games.Where(s => s.RecommendCount!.Contains(numPlayers));
                    ViewBag.BestGames = games.Where(s => s.BestCount!.Contains(numPlayers));*/
                }
                else if (numQuality == "best")
                {
                    games = games.Where(s => s.BestCount!.Contains(numPlayers)).OrderByDescending(game => game.Rating);
/*                    ViewBag.BestGames = games.Where(s => s.BestCount!.Contains(numPlayers));*/
                }
            }

            return View(await games.ToListAsync());
        }

        // GET: Games/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var game = await _context.Game
                .FirstOrDefaultAsync(m => m.Id == id);
            if (game == null)
            {
                return NotFound();
            }

            return View(game);
        }

        // GET: Games/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Games/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Rating,RecommendCount,BestCount,SupportCount,Link")] Game game)
        {
            if (ModelState.IsValid)
            {
                _context.Add(game);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(game);
        }

        // GET: Games/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var game = await _context.Game.FindAsync(id);
            if (game == null)
            {
                return NotFound();
            }
            return View(game);
        }

        // POST: Games/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Rating,RecommendCount,BestCount,SupportCount,Link")] Game game)
        {
            if (id != game.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(game);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GameExists(game.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(game);
        }

        // GET: Games/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var game = await _context.Game
                .FirstOrDefaultAsync(m => m.Id == id);
            if (game == null)
            {
                return NotFound();
            }

            return View(game);
        }

        // POST: Games/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var game = await _context.Game.FindAsync(id);
            _context.Game.Remove(game);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GameExists(int id)
        {
            return _context.Game.Any(e => e.Id == id);
        }
    }
}

BGAWebApp/Views/Games/Create.cshtml
@model BGAWebApp.Models.Game

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Game</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rating" class="control-label"></label>
                <input asp-for="Rating" class="form-control" />
                <span asp-validation-for="Rating" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RecommendCount" class="control-label"></label>
                <input asp-for="RecommendCount" class="form-control" />
                <span asp-validation-for="RecommendCount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BestCount" class="control-label"></label>
                <input asp-for="BestCount" class="form-control" />
                <span asp-validation-for="BestCount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BGAWebApp/Views/Games/Delete.cshtml
@model BGAWebApp.Models.Game

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Game</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Rating)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Rating)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RecommendCount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RecommendCount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BestCount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BestCount)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

BGAWebApp/Views/Games/Details.cshtml
@model BGAWebApp.Models.Game

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Game</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Rating)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Rating)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RecommendCount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RecommendCount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BestCount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BestCount)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

BGAWebApp/Views/Games/Edit.cshtml
@model BGAWebApp.Models.Game

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Game</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rating" class="control-label"></label>
                <input asp-for="Rating" class="form-control" />
                <span asp-validation-for="Rating" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RecommendCount" class="control-label"></label>
                <input asp-for="RecommendCount" class="form-control" />
                <span asp-validation-for="RecommendCount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BestCount" class="control-label"></label>
                <input asp-for="BestCount" class="form-control" />
                <span asp-validation-for="BestCount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BGAWebApp/Views/Games/Index.cshtml
@model IEnumerable<BGAWebApp.Models.Game>

@{
    ViewData["Title"] = "Index";
}

<h1>Games</h1>

<form asp-controller="Games" asp-action="Index" method="get">
<p>
    <label for="numPlayers">Number of players:</label>
    <input type="text" name="numPlayers" />
</p>
@Html.RadioButton("numQuality", "best") Best <br />
@Html.RadioButton("numQuality", "recommend") Recommended + Best <br />
@Html.RadioButton("numQuality", "support") Supported + Recommended + Best <br />
<input type="submit" value="Filter" />
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Rating)
            </th>
            @if (ViewBag.numPlayers != null)
            {
                <th>
                    Quality at @ViewBag.numPlayers players
                </th>
            }
           
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                <a href="@Html.DisplayFor(modelItem => item.Link)">@Html.DisplayFor(modelItem => item.Title)</a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Rating)
            </td>
            @if (ViewBag.numPlayers == null)
            {
                    
            }
            else if (item.BestCount!.Contains(ViewBag.numPlayers))
                {
                    <td id="best">
                        <span>Best!</span>
                    </td>
                }
            else if (item.RecommendCount!.Contains(ViewBag.numPlayers))
                {
                    <td id="recommend">
                        <span>Recommended</span>
                    </td>

                }
            else if (item.SupportCount!.Contains(ViewBag.numPlayers))
                {
                    <td id="support">
                        <span>Supported</span>
                    </td>
                }
        </tr>
}
    </tbody>
</table>